version: '3.8'

services:
  # 1. PostgreSQL - Database chính
  postgres:
    image: postgres:15-alpine
    container_name: ecom-postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: ecomerce
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Redis - Cache / Message Broker (tùy chọn)
  redis:
    image: redis:7-alpine
    container_name: ecom-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # 3. ElasticSearch - Full-text Search (Tìm kiếm sản phẩm)
  elasticsearch:
    image: elasticsearch:8.10.2
    container_name: ecom-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Tắt bảo mật để tiện dev local
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # Giới hạn RAM tránh treo máy
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data

volumes:
  postgres_data:
  redis_data:
  es_data:
